### ISSUE TITLE
seeds per fruit?

### ISSUE THREAD

**Issue by texmiller** [TrevorHD/LTEncroachment#5]
We need to confirm how many seeds per fruit. For now I am coding the IPM with this parameter hard-coded to 6.

**Comment by TrevorHD** [comment]
Several sources I found, including [this one](https://www.fs.fed.us/database/feis/plants/shrub/lartri/all.html) from the USDA, say that there are typically 5 seeds per fruit. Will leave this issue open for now until we see how much of a difference this makes in the model.

**Comment by texmiller** [comment]
Let's go with 5 then. Probably will not make a big difference.
